List vehicleMake = [
  {
    "id": 1,
    "brand": "Acura",
    "models": [
      {"id": 1, "name": "2.2CL"},
      {"id": 2, "name": "2.3CL"},
      {"id": 3, "name": "3.0CL"},
      {"id": 4, "name": "3.2CL"},
      {"id": 5, "name": "ILX"},
      {"id": 6, "name": "Integra"},
      {"id": 7, "name": "Legend"},
      {"id": 8, "name": "MDX"},
      {"id": 9, "name": "NSX"},
      {"id": 10, "name": "RDX"},
      {"id": 11, "name": "3.5 RL"},
      {"id": 12, "name": "RL"},
      {"id": 13, "name": "RSX"},
      {"id": 14, "name": "SLX"},
      {"id": 15, "name": "2.5TL"},
      {"id": 16, "name": "3.2TL"},
      {"id": 17, "name": "TL"},
      {"id": 18, "name": "TSX"},
      {"id": 19, "name": "Vigor"},
      {"id": 20, "name": "ZDX"}
    ]
  },
  {
    "id": 2,
    "brand": "Alfa Romeo",
    "models": [
      {"id": 1, "name": "164"},
      {"id": 2, "name": "8C Competizione"},
      {"id": 3, "name": "GTV-6"},
      {"id": 4, "name": "Milano"},
      {"id": 5, "name": "Spider"}
    ]
  },
  {
    "id": 3,
    "brand": "AMC",
    "models": [
      {"id": 1, "name": "Alliance"},
      {"id": 2, "name": "Concord"},
      {"id": 3, "name": "Eagle"},
      {"id": 4, "name": "Encore"},
      {"id": 5, "name": "Spirit"}
    ]
  },
  {
    "id": 4,
    "brand": "Aston Martin",
    "models": [
      {"id": 1, "name": "DB7"},
      {"id": 2, "name": "DB9"},
      {"id": 3, "name": "DBS"},
      {"id": 4, "name": "Lagonda"},
      {"id": 5, "name": "Rapide"},
      {"id": 6, "name": "V12 Vantage"},
      {"id": 7, "name": "V8 Vantage"},
      {"id": 8, "name": "Vanquish"},
      {"id": 9, "name": "Virage"}
    ]
  },
  {
    "id": 5,
    "brand": "Audi",
    "models": [
      "100",
      "200",
      "4000",
      "5000",
      "80",
      "90",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "allroad",
      "Cabriolet",
      "Coupe",
      "Q3",
      "Q5",
      "Q7",
      "Quattro",
      "R8",
      "RS 4",
      "RS 5",
      "RS 6",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "TT",
      "TT RS",
      "TTS",
      "V8 Quattro"
    ]
  },
  {
    "id": 6,
    "brand": "Avanti",
    "models": [
      {"id": 1, "name": "Convertible"},
      {"id": 2, "name": "Coupe"},
      {"id": 3, "name": "Sedan"}
    ]
  },
  {
    "id": 7,
    "brand": "Bentley",
    "models": [
      "Arnage",
      "Azure",
      "Brooklands",
      "Continental",
      "Corniche",
      "Eight",
      "Mulsanne",
      "Turbo R"
    ]
  },
  {
    "id": 8,
    "brand": "BMW",
    "models": [
      "128i",
      "135i",
      "135is",
      "318i",
      "318iC",
      "318iS",
      "318ti",
      "320i",
      "323ci",
      "323i",
      "323is",
      "323iT",
      "325Ci",
      "325e",
      "325es",
      "325i",
      "325is",
      "325iX",
      "325xi",
      "328Ci",
      "328i",
      "328iS",
      "328xi",
      "330Ci",
      "330i",
      "330xi",
      "335d",
      "335i",
      "335is",
      "335xi",
      "ActiveHybrid 3",
      "325",
      "524td",
      "525i",
      "525xi",
      "528e",
      "528i",
      "528iT",
      "528xi",
      "530i",
      "530iT",
      "530xi",
      "533i",
      "535i",
      "535i Gran Turismo",
      "535xi",
      "540i",
      "545i",
      "550i",
      "550i Gran Turismo",
      "ActiveHybrid 5",
      "633CSi",
      "635CSi",
      "640i",
      "640i Gran Coupe",
      "645Ci",
      "650i",
      "650i Gran Coupe",
      "L6",
      "733i",
      "735i",
      "735iL",
      "740i",
      "740iL",
      "740Li",
      "745i",
      "745Li",
      "750i",
      "750iL",
      "750Li",
      "760i",
      "760Li",
      "ActiveHybrid 7",
      "Alpina B7",
      "840Ci",
      "850Ci",
      "850CSi",
      "850i",
      "L7",
      "1 Series M",
      "M Coupe",
      "M Roadster",
      "M3",
      "M5",
      "M6",
      "X5 M",
      "X6 M",
      "ActiveHybrid X6",
      "X1",
      "X3",
      "X5",
      "X6",
      "Z3",
      "Z4",
      "Z8"
    ]
  },
  {
    "id": 9,
    "brand": "Buick",
    "models": [
      "Century",
      "Electra",
      "Enclave",
      "Encore",
      "LaCrosse",
      "Le Sabre",
      "Lucerne",
      "Park Avenue",
      "Rainier",
      "Reatta",
      "Regal",
      "Rendezvous",
      "Riviera",
      "Roadmaster",
      "Skyhawk",
      "Skylark",
      "Somerset",
      "Terraza",
      "Verano"
    ]
  },
  {
    "id": 10,
    "brand": "Cadillac",
    "models": [
      "Allante",
      "ATS",
      "Brougham",
      "Catera",
      "Cimarron",
      "CTS",
      "De Ville",
      "DTS",
      "Eldorado",
      "Escalade",
      "Escalade ESV",
      "Escalade EXT",
      "Fleetwood",
      "Seville",
      "SRX",
      "STS",
      "XLR",
      "XTS"
    ]
  },
  {
    "id": 11,
    "brand": "Chevrolet",
    "models": [
      "Astro",
      "Avalanche",
      "Aveo",
      "Aveo5",
      "Beretta",
      "Blazer",
      "Camaro",
      "Caprice",
      "Captiva Sport",
      "Cavalier",
      "Celebrity",
      "Chevette",
      "Citation",
      "Cobalt",
      "Colorado",
      "Corsica",
      "Corvette",
      "Cruze",
      "El Camino",
      "Equinox",
      "Express Van",
      "G Van",
      "HHR",
      "Impala",
      "Kodiak C4500",
      "Lumina",
      "Lumina APV",
      "LUV",
      "Malibu",
      "Metro",
      "Monte Carlo",
      "Nova",
      "Prizm",
      "S10 Blazer",
      "S10 Pickup",
      "Silverado and other C/K1500",
      "Silverado and other C/K2500",
      "Silverado and other C/K3500",
      "Sonic",
      "Spark",
      "Spectrum",
      "Sprint",
      "SSR",
      "Suburban",
      "Tahoe",
      "Tracker",
      "TrailBlazer",
      "TrailBlazer EXT",
      "Traverse",
      "Uplander",
      "Venture",
      "Volt"
    ]
  },
  {
    "id": 12,
    "brand": "Chrysler",
    "models": [
      "200",
      "300",
      "300M",
      "Aspen",
      "Caravan",
      "Cirrus",
      "Concorde",
      "Conquest",
      "Cordoba",
      "Crossfire",
      "E Class",
      "Fifth Avenue",
      "Grand Voyager",
      "Imperial",
      "Intrepid",
      "Laser",
      "LeBaron",
      "LHS",
      "Neon",
      "New Yorker",
      "Newport",
      "Pacifica",
      "Prowler",
      "PT Cruiser",
      "Sebring",
      "TC by Maserati",
      "Town &amp; Country",
      "Voyager"
    ]
  },
  {
    "id": 13,
    "brand": "Daewoo",
    "models": [
      {"id": 1, "name": "Lanos"},
      {"id": 2, "name": "Leganza"},
      {"id": 3, "name": "Nubira"}
    ]
  },
  {
    "id": 14,
    "brand": "Daihatsu",
    "models": [
      {"id": 1, "name": "Charade"},
      {"id": 2, "name": "Rocky"}
    ]
  },
  {
    "id": 15,
    "brand": "Datsun",
    "models": [
      "200SX",
      "210",
      "280ZX",
      "300ZX",
      "310",
      "510",
      "720",
      "810",
      "Maxima",
      "Pickup",
      "Pulsar",
      "Sentra",
      "Stanza"
    ]
  },
  {
    "id": 16,
    "brand": "DeLorean",
    "models": ["DMC-12"]
  },
  {
    "id": 17,
    "brand": "Dodge",
    "models": [
      "400",
      "600",
      "Aries",
      "Avenger",
      "Caliber",
      "Caravan",
      "Challenger",
      "Charger",
      "Colt",
      "Conquest",
      "D/W Truck",
      "Dakota",
      "Dart",
      "Daytona",
      "Diplomat",
      "Durango",
      "Dynasty",
      "Grand Caravan",
      "Intrepid",
      "Journey",
      "Lancer",
      "Magnum",
      "Mirada",
      "Monaco",
      "Neon",
      "Nitro",
      "Omni",
      "Raider",
      "Ram 1500 Truck",
      "Ram 2500 Truck",
      "Ram 3500 Truck",
      "Ram 4500 Truck",
      "Ram 50 Truck",
      "RAM C/V",
      "Ram SRT-10",
      "Ram Van",
      "Ram Wagon",
      "Ramcharger",
      "Rampage",
      "Shadow",
      "Spirit",
      "Sprinter",
      "SRT-4",
      "St. Regis",
      "Stealth",
      "Stratus",
      "Viper"
    ]
  },
  {
    "id": 18,
    "brand": "Eagle",
    "models": ["Medallion", "Premier", "Summit", "Talon", "Vision"]
  },
  {
    "id": 19,
    "brand": "Ferrari",
    "models": [
      "308 GTB Quattrovalvole",
      "308 GTBI",
      "308 GTS Quattrovalvole",
      "308 GTSI",
      "328 GTB",
      "328 GTS",
      "348 GTB",
      "348 GTS",
      "348 Spider",
      "348 TB",
      "348 TS",
      "360",
      "456 GT",
      "456M GT",
      "458 Italia",
      "512 BBi",
      "512M",
      "512TR",
      "550 Maranello",
      "575M Maranello",
      "599 GTB Fiorano",
      "599 GTO",
      "612 Scaglietti",
      "California",
      "Enzo",
      "F355",
      "F40",
      "F430",
      "F50",
      "FF",
      "Mondial",
      "Testarossa"
    ]
  },
  {
    "id": 21,
    "brand": "Fisker",
    "models": ["Karma"]
  },
  {
    "id": 22,
    "brand": "Ford",
    "models": [
      "Aerostar",
      "Aspire",
      "Bronco",
      "Bronco II",
      "C-MAX",
      "Club Wagon",
      "Contour",
      "Courier",
      "Crown Victoria",
      "E-150 and Econoline 150",
      "E-250 and Econoline 250",
      "E-350 and Econoline 350",
      "Edge",
      "Escape",
      "Escort",
      "Excursion",
      "EXP",
      "Expedition",
      "Expedition EL",
      "Explorer",
      "Explorer Sport Trac",
      "F100",
      "F150",
      "F250",
      "F350",
      "F450",
      "Fairmont",
      "Festiva",
      "Fiesta",
      "Five Hundred",
      "Flex",
      "Focus",
      "Freestar",
      "Freestyle",
      "Fusion",
      "Granada",
      "GT",
      "LTD",
      "Mustang",
      "Probe",
      "Ranger",
      "Taurus",
      "Taurus X",
      "Tempo",
      "Thunderbird",
      "Transit Connect",
      "Windstar",
      "ZX2 Escort"
    ]
  },
  {
    "id": 23,
    "brand": "Freightliner",
    "models": ["Sprinter"]
  },
  {
    "id": 24,
    "brand": "Geo",
    "models": ["Metro", "Prizm", "Spectrum", "Storm", "Tracker"]
  },
  {
    "id": 25,
    "brand": "GMC",
    "models": [
      "Acadia",
      "Caballero",
      "Canyon",
      "Envoy",
      "Envoy XL",
      "Envoy XUV",
      "Jimmy",
      "Rally Wagon",
      "S15 Jimmy",
      "S15 Pickup",
      "Safari",
      "Savana",
      "Sierra C/K1500",
      "Sierra C/K2500",
      "Sierra C/K3500",
      "Sonoma",
      "Suburban",
      "Syclone",
      "Terrain",
      "TopKick C4500",
      "Typhoon",
      "Vandura",
      "Yukon",
      "Yukon XL"
    ]
  },
  {
    "id": 27,
    "brand": "HUMMER",
    "models": ["H1", "H2", "H3", "H3T"]
  },
  {
    "id": 29,
    "brand": "Infiniti",
    "models": [
      "EX35",
      "EX37",
      "FX35",
      "FX37",
      "FX45",
      "FX50",
      "G20",
      "G25",
      "G35",
      "G37",
      "I30",
      "I35",
      "J30",
      "JX35",
      "M30",
      "M35",
      "M35h",
      "M37",
      "M45",
      "M56",
      "Q45",
      "QX4",
      "QX56"
    ]
  },
  {
    "id": 30,
    "brand": "Isuzu",
    "models": [
      "Amigo",
      "Ascender",
      "Axiom",
      "Hombre",
      "i-280",
      "i-290",
      "i-350",
      "i-370",
      "I-Mark",
      "Impulse",
      "Oasis",
      "Pickup",
      "Rodeo",
      "Stylus",
      "Trooper",
      "Trooper II",
      "VehiCROSS"
    ]
  },
  {
    "id": 32,
    "brand": "Jeep",
    "models": [
      "Cherokee",
      "CJ",
      "Comanche",
      "Commander",
      "Compass",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty",
      "Patriot",
      "Pickup",
      "Scrambler",
      "Wagoneer",
      "Wrangler"
    ]
  },
  {
    "id": 34,
    "brand": "Lamborghini",
    "models": [
      "Aventador",
      "Countach",
      "Diablo",
      "Gallardo",
      "Jalpa",
      "LM002",
      "Murcielago"
    ]
  },
  {
    "id": 35,
    "brand": "Lancia",
    "models": ["Beta", "Zagato"]
  },
  {
    "id": 36,
    "brand": "Land Rover",
    "models": [
      "Defender",
      "Discovery",
      "Freelander",
      "LR2",
      "LR3",
      "LR4",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport"
    ]
  },
  {
    "id": 37,
    "brand": "Lexus",
    "models": [
      "CT 200h",
      "ES 250",
      "ES 300",
      "ES 300h",
      "ES 330",
      "ES 350",
      "GS 300",
      "GS 350",
      "GS 400",
      "GS 430",
      "GS 450h",
      "GS 460",
      "GX 460",
      "GX 470",
      "HS 250h",
      "IS 250",
      "IS 250C",
      "IS 300",
      "IS 350",
      "IS 350C",
      "IS F",
      "LFA",
      "LS 400",
      "LS 430",
      "LS 460",
      "LS 600h",
      "LX 450",
      "LX 470",
      "LX 570",
      "RX 300",
      "RX 330",
      "RX 350",
      "RX 400h",
      "RX 450h",
      "SC 300",
      "SC 400",
      "SC 430"
    ]
  },
  {
    "id": 38,
    "brand": "Lincoln",
    "models": [
      "Aviator",
      "Blackwood",
      "Continental",
      "LS",
      "Mark LT",
      "Mark VI",
      "Mark VII",
      "Mark VIII",
      "MKS",
      "MKT",
      "MKX",
      "MKZ",
      "Navigator",
      "Navigator L",
      "Town Car",
      "Zephyr"
    ]
  },
  {
    "id": 39,
    "brand": "Lotus",
    "models": ["Elan", "Elise", "Esprit", "Evora", "Exige"]
  },
  {
    "id": 40,
    "brand": "Maserati",
    "models": [
      "430",
      "Biturbo",
      "Coupe",
      "GranSport",
      "GranTurismo",
      "Quattroporte",
      "Spyder"
    ]
  },
  {
    "id": 41,
    "brand": "Maybach",
    "models": ["57", "62"]
  },
  {
    "id": 43,
    "brand": "McLaren",
    "models": ["MP4-12C"]
  },
  {
    "id": 44,
    "brand": "Mercedes-Benz",
    "models": [
      "190D",
      "190E",
      "240D",
      "300CD",
      "300CE",
      "300D",
      "300E",
      "300TD",
      "300TE",
      "C220",
      "C230",
      "C240",
      "C250",
      "C280",
      "C300",
      "C320",
      "C32 AMG",
      "C350",
      "C36 AMG",
      "C43 AMG",
      "C55 AMG",
      "C63 AMG",
      "CL500",
      "CL550",
      "CL55 AMG",
      "CL600",
      "CL63 AMG",
      "CL65 AMG",
      "CLK320",
      "CLK350",
      "CLK430",
      "CLK500",
      "CLK550",
      "CLK55 AMG",
      "CLK63 AMG",
      "CLS500",
      "CLS550",
      "CLS55 AMG",
      "CLS63 AMG",
      "260E",
      "280CE",
      "280E",
      "400E",
      "500E",
      "E300",
      "E320",
      "E320 Bluetec",
      "E320 CDI",
      "E350",
      "E350 Bluetec",
      "E400 Hybrid",
      "E420",
      "E430",
      "E500",
      "E550",
      "E55 AMG",
      "E63 AMG",
      "G500",
      "G550",
      "G55 AMG",
      "G63 AMG",
      "GL320 Bluetec",
      "GL320 CDI",
      "GL350 Bluetec",
      "GL450",
      "GL550",
      "GLK350",
      "ML320",
      "ML320 Bluetec",
      "ML320 CDI",
      "ML350",
      "ML350 Bluetec",
      "ML430",
      "ML450 Hybrid",
      "ML500",
      "ML550",
      "ML55 AMG",
      "ML63 AMG",
      "R320 Bluetec",
      "R320 CDI",
      "R350",
      "R350 Bluetec",
      "R500",
      "R63 AMG",
      "300SD",
      "300SDL",
      "300SE",
      "300SEL",
      "350SD",
      "350SDL",
      "380SE",
      "380SEC",
      "380SEL",
      "400SE",
      "400SEL",
      "420SEL",
      "500SEC",
      "500SEL",
      "560SEC",
      "560SEL",
      "600SEC",
      "600SEL",
      "S320",
      "S350",
      "S350 Bluetec",
      "S400 Hybrid",
      "S420",
      "S430",
      "S500",
      "S550",
      "S55 AMG",
      "S600",
      "S63 AMG",
      "S65 AMG",
      "300SL",
      "380SL",
      "380SLC",
      "500SL",
      "560SL",
      "600SL",
      "SL320",
      "SL500",
      "SL550",
      "SL55 AMG",
      "SL600",
      "SL63 AMG",
      "SL65 AMG",
      "SLK230",
      "SLK250",
      "SLK280",
      "SLK300",
      "SLK320",
      "SLK32 AMG",
      "SLK350",
      "SLK55 AMG",
      "SLR",
      "SLS AMG",
      "Sprinter"
    ]
  },
  {
    "id": 45,
    "brand": "Mercury",
    "models": [
      "Capri",
      "Cougar",
      "Grand Marquis",
      "Lynx",
      "Marauder",
      "Mariner",
      "Marquis",
      "Milan",
      "Montego",
      "Monterey",
      "Mountaineer",
      "Mystique",
      "Sable",
      "Topaz",
      "Tracer",
      "Villager",
      "Zephyr"
    ]
  },
  {
    "id": 46,
    "brand": "Merkur",
    "models": ["Scorpio", "XR4Ti"]
  },
  {
    "id": 47,
    "brand": "MINI",
    "models": [
      "Cooper Clubman",
      "Cooper S Clubman",
      "Cooper Countryman",
      "Cooper S Countryman",
      "Cooper Coupe",
      "Cooper S Coupe",
      "Cooper",
      "Cooper S",
      "Cooper Roadster",
      "Cooper S Roadster"
    ]
  },
  {
    "id": 49,
    "brand": "Nissan",
    "models": [
      "200SX",
      "240SX",
      "300ZX",
      "350Z",
      "370Z",
      "Altima",
      "Armada",
      "Axxess",
      "Cube",
      "Frontier",
      "GT-R",
      "Juke",
      "Leaf",
      "Maxima",
      "Murano",
      "Murano CrossCabriolet",
      "NV",
      "NX",
      "Pathfinder",
      "Pickup",
      "Pulsar",
      "Quest",
      "Rogue",
      "Sentra",
      "Stanza",
      "Titan",
      "Van",
      "Versa",
      "Xterra"
    ]
  },
  {
    "id": 50,
    "brand": "Oldsmobile",
    "models": [
      "88",
      "Achieva",
      "Alero",
      "Aurora",
      "Bravada",
      "Custom Cruiser",
      "Cutlass",
      "Cutlass Calais",
      "Cutlass Ciera",
      "Cutlass Supreme",
      "Firenza",
      "Intrigue",
      "Ninety-Eight",
      "Omega",
      "Regency",
      "Silhouette",
      "Toronado"
    ]
  },
  {
    "id": 52,
    "brand": "Plymouth",
    "models": [
      "Acclaim",
      "Arrow",
      "Breeze",
      "Caravelle",
      "Champ",
      "Colt",
      "Conquest",
      "Gran Fury",
      "Grand Voyager",
      "Horizon",
      "Laser",
      "Neon",
      "Prowler",
      "Reliant",
      "Sapporo",
      "Scamp",
      "Sundance",
      "Trailduster",
      "Voyager"
    ]
  },
  {
    "id": 53,
    "brand": "Pontiac",
    "models": [
      "1000",
      "6000",
      "Aztek",
      "Bonneville",
      "Catalina",
      "Fiero",
      "Firebird",
      "G3",
      "G5",
      "G6",
      "G8",
      "Grand Am",
      "Grand Prix",
      "GTO",
      "J2000",
      "Le Mans",
      "Montana",
      "Parisienne",
      "Phoenix",
      "Safari",
      "Solstice",
      "Sunbird",
      "Sunfire",
      "Torrent",
      "Trans Sport",
      "Vibe"
    ]
  },
  {
    "id": 54,
    "brand": "Porsche",
    "models": [
      "911",
      "924",
      "928",
      "944",
      "968",
      "Boxster",
      "Carrera GT",
      "Cayenne",
      "Cayman",
      "Panamera"
    ]
  },
  {
    "id": 55,
    "brand": "RAM",
    "models": ["1500", "2500", "3500", "4500"]
  },
  {
    "id": 57,
    "brand": "Rolls-Royce",
    "models": [
      "Camargue",
      "Corniche",
      "Ghost",
      "Park Ward",
      "Phantom",
      "Silver Dawn",
      "Silver Seraph",
      "Silver Spirit",
      "Silver Spur"
    ]
  },
  {
    "id": 59,
    "brand": "Saturn",
    "models": [
      "Astra",
      "Aura",
      "ION",
      "L100",
      "L200",
      "L300",
      "LS",
      "LW1",
      "LW2",
      "LW200",
      "LW300",
      "Outlook",
      "Relay",
      "SC1",
      "SC2",
      "Sky",
      "SL",
      "SL1",
      "SL2",
      "SW1",
      "SW2",
      "Vue"
    ]
  },
  {
    "id": 60,
    "brand": "Scion",
    "models": ["FR-S", "iQ", "tC", "xA", "xB", "xD"]
  },
  {
    "id": 62,
    "brand": "SRT",
    "models": ["Viper"]
  },
  {
    "id": 63,
    "brand": "Sterling",
    "models": ["825", "827"]
  },
  {
    "id": 64,
    "brand": "Subaru",
    "models": [
      "Baja",
      "Brat",
      "BRZ",
      "Forester",
      "Impreza",
      "Impreza WRX",
      "Justy",
      "L Series",
      "Legacy",
      "Loyale",
      "Outback",
      "SVX",
      "Tribeca",
      "XT",
      "XV Crosstrek"
    ]
  },
  {
    "id": 66,
    "brand": "Tesla",
    "models": ["Roadster", "Model S"]
  },
  {
    "id": 67,
    "brand": "Toyota",
    "models": [
      "4Runner",
      "Avalon",
      "Camry",
      "Celica",
      "Corolla",
      "Corona",
      "Cressida",
      "Echo",
      "FJ Cruiser",
      "Highlander",
      "Land Cruiser",
      "Matrix",
      "MR2",
      "MR2 Spyder",
      "Paseo",
      "Pickup",
      "Previa",
      "Prius",
      "Prius C",
      "Prius V",
      "RAV4",
      "Sequoia",
      "Sienna",
      "Solara",
      "Starlet",
      "Supra",
      "T100",
      "Tacoma",
      "Tercel",
      "Tundra",
      "Van",
      "Venza",
      "Yaris"
    ]
  },
  {
    "id": 68,
    "brand": "Triumph",
    "models": ["TR7", "TR8"]
  },
  {
    "id": 71,
    "brand": "Yugo",
    "models": ["GV", "GVC", "GVL", "GVS", "GVX"]
  },
  {
    "id": 72,
    "brand": "Seat",
    "models": [
      "Alhambra",
      "Altea",
      "Altea XL",
      "Arosa",
      "Cordoba",
      "Cordoba Vario",
      "Exeo",
      "Ibiza",
      "Ibiza ST",
      "Exeo ST",
      "Leon",
      "Leon ST",
      "Inca",
      "Mii",
      "Toledo"
    ]
  },
  {
    "id": 73,
    "brand": "Renault",
    "models": [
      "Captur",
      "Clio",
      "Clio Grandtour",
      "Espace",
      "Express",
      "Fluence",
      "Grand Espace",
      "Grand Modus",
      "Grand Scenic",
      "Kadjar",
      "Kangoo",
      "Kangoo Express",
      "Koleos",
      "Laguna",
      "Laguna Grandtour",
      "Latitude",
      "Mascott",
      "Mégane",
      "Mégane CC",
      "Mégane Combi",
      "Mégane Grandtour",
      "Mégane Coupé",
      "Mégane Scénic",
      "Scénic",
      "Talisman",
      "Talisman Grandtour",
      "Thalia",
      "Twingo",
      "Wind",
      "Zoé"
    ]
  },
  {
    "id": 74,
    "brand": "Peugeot",
    "models": [
      "1007",
      "107",
      "106",
      "108",
      "2008",
      "205",
      "205 Cabrio",
      "206",
      "206 CC",
      "206 SW",
      "207",
      "207 CC",
      "207 SW",
      "306",
      "307",
      "307 CC",
      "307 SW",
      "308",
      "308 CC",
      "308 SW",
      "309",
      "4007",
      "4008",
      "405",
      "406",
      "407",
      "407 SW",
      "5008",
      "508",
      "508 SW",
      "605",
      "806",
      "607",
      "807",
      "Bipper",
      "RCZ"
    ]
  },
  {
    "id": 75,
    "brand": "Dacia",
    "models": [
      "Dokker",
      "Duster",
      "Lodgy",
      "Logan",
      "Logan MCV",
      "Logan Van",
      "Sandero",
      "Solenza"
    ]
  },
  {
    "id": 76,
    "brand": "Citroën",
    "models": [
      "Berlingo",
      "C-Crosser",
      "C-Elissée",
      "C-Zero",
      "C1",
      "C2",
      "C3",
      "C3 Picasso",
      "C4",
      "C4 Aircross",
      "C4 Cactus",
      "C4 Coupé",
      "C4 Grand Picasso",
      "C4 Sedan",
      "C5",
      "C5 Break",
      "C5 Tourer",
      "C6",
      "C8",
      "DS3",
      "DS4",
      "DS5",
      "Evasion",
      "Jumper",
      "Jumpy",
      "Saxo",
      "Nemo",
      "Xantia",
      "Xsara"
    ]
  },
  {
    "id": 77,
    "brand": "Opel",
    "models": [
      "Agila",
      "Ampera",
      "Antara",
      "Astra",
      "Astra cabrio",
      "Astra caravan",
      "Astra coupé",
      "Calibra",
      "Campo",
      "Cascada",
      "Corsa",
      "Frontera",
      "Insignia",
      "Insignia kombi",
      "Kadett",
      "Meriva",
      "Mokka",
      "Movano",
      "Omega",
      "Signum",
      "Vectra",
      "Vectra Caravan",
      "Vivaro",
      "Vivaro Kombi",
      "Zafira"
    ]
  },
  {
    "id": 79,
    "brand": "Skoda",
    "models": [
      "Favorit",
      "Felicia",
      "Citigo",
      "Fabia",
      "Fabia Combi",
      "Fabia Sedan",
      "Felicia Combi",
      "Octavia",
      "Octavia Combi",
      "Roomster",
      "Yeti",
      "Rapid",
      "Rapid Spaceback",
      "Superb",
      "Superb Combi"
    ]
  },
  {
    "id": 82,
    "brand": "Honda",
    "models": [
      "Accord",
      "Accord Coupé",
      "Accord Tourer",
      "City",
      "Civic",
      "Civic Aerodeck",
      "Civic Coupé",
      "Civic Tourer",
      "Civic Type R",
      "CR-V",
      "CR-X",
      "CR-Z",
      "FR-V",
      "HR-V",
      "Insight",
      "Integra",
      "Jazz",
      "Legend",
      "Prelude"
    ]
  },
  {
    "id": 84,
    "brand": "Mazda",
    "models": [
      "121",
      "2",
      "3",
      "323",
      "323 Combi",
      "323 Coupé",
      "323 F",
      "5",
      "6",
      "6 Combi",
      "626",
      "626 Combi",
      "B-Fighter",
      "B2500",
      "BT",
      "CX-3",
      "CX-5",
      "CX-7",
      "CX-9",
      "Demio",
      "MPV",
      "MX-3",
      "MX-5",
      "MX-6",
      "Premacy",
      "RX-7",
      "RX-8",
      "Xedox 6"
    ]
  },
  {
    "id": 85,
    "brand": "Mitsubishi",
    "models": [
      "3000 GT",
      "ASX",
      "Carisma",
      "Colt",
      "Colt CC",
      "Eclipse",
      "Fuso canter",
      "Galant",
      "Galant Combi",
      "Grandis",
      "L200",
      "L200 Pick up",
      "L200 Pick up Allrad",
      "L300",
      "Lancer",
      "Lancer Combi",
      "Lancer Evo",
      "Lancer Sportback",
      "Outlander",
      "Pajero",
      "Pajeto Pinin",
      "Pajero Pinin Wagon",
      "Pajero Sport",
      "Pajero Wagon",
      "Space Star"
    ]
  },
  {
    "id": 89,
    "brand": "Volkswagen",
    "models": [
      "Amarok",
      "Beetle",
      "Bora",
      "Bora Variant",
      "Caddy",
      "Caddy Van",
      "Life",
      "California",
      "Caravelle",
      "CC",
      "Crafter",
      "Crafter Van",
      "Crafter Kombi",
      "CrossTouran",
      "Eos",
      "Fox",
      "Golf",
      "Golf Cabrio",
      "Golf Plus",
      "Golf Sportvan",
      "Golf Variant",
      "Jetta",
      "LT",
      "Lupo",
      "Multivan",
      "New Beetle",
      "New Beetle Cabrio",
      "Passat",
      "Passat Alltrack",
      "Passat CC",
      "Passat Variant",
      "Passat Variant Van",
      "Phaeton",
      "Polo",
      "Polo Van",
      "Polo Variant",
      "Scirocco",
      "Sharan",
      "T4",
      "T4 Caravelle",
      "T4 Multivan",
      "T5",
      "T5 Caravelle",
      "T5 Multivan",
      "T5 Transporter Shuttle",
      "Tiguan",
      "Touareg",
      "Touran"
    ]
  },
  {
    "id": 90,
    "brand": "Suzuki",
    "models": [
      "Alto",
      "Baleno",
      "Baleno kombi",
      "Grand Vitara",
      "Grand Vitara XL-7",
      "Ignis",
      "Jimny",
      "Kizashi",
      "Liana",
      "Samurai",
      "Splash",
      "Swift",
      "SX4",
      "SX4 Sedan",
      "Vitara",
      "Wagon R+"
    ]
  },
  {
    "id": 92,
    "brand": "Saab",
    "models": [
      "9-3",
      "9-3 Cabriolet",
      "9-3 Coupé",
      "9-3 SportCombi",
      "9-5",
      "9-5 SportCombi",
      "900",
      "900 C",
      "900 C Turbo",
      "9000"
    ]
  },
  {
    "id": 94,
    "brand": "Kia",
    "models": [
      "Avella",
      "Besta",
      "Carens",
      "Carnival",
      "Cee`d",
      "Cee`d SW",
      "Cerato",
      "K 2500",
      "Magentis",
      "Opirus",
      "Optima",
      "Picanto",
      "Pregio",
      "Pride",
      "Pro Cee`d",
      "Rio",
      "Rio Combi",
      "Rio sedan",
      "Sephia",
      "Shuma",
      "Sorento",
      "Soul",
      "Sportage",
      "Venga"
    ]
  },
  {
    "id": 100,
    "brand": "Hyundai",
    "models": [
      "Accent",
      "Atos",
      "Atos Prime",
      "Coupé",
      "Elantra",
      "Galloper",
      "Genesis",
      "Getz",
      "Grandeur",
      "H 350",
      "H1",
      "H1 Bus",
      "H1 Van",
      "H200",
      "i10",
      "i20",
      "i30",
      "i30 CW",
      "i40",
      "i40 CW",
      "ix20",
      "ix35",
      "ix55",
      "Lantra",
      "Matrix",
      "Santa Fe",
      "Sonata",
      "Terracan",
      "Trajet",
      "Tucson",
      "Veloster"
    ]
  },
  {
    "id": 102,
    "brand": "Jaguar",
    "models": [
      "Daimler",
      "F-Pace",
      "F-Type",
      "S-Type",
      "Sovereign",
      "X-Type",
      "X-type Estate",
      "XE",
      "XF",
      "XJ",
      "XJ12",
      "XJ6",
      "XJ8",
      "XJ8",
      "XJR",
      "XK",
      "XK8 Convertible",
      "XKR",
      "XKR Convertible"
    ]
  },
  {
    "id": 105,
    "brand": "Volvo",
    "models": [
      "240",
      "340",
      "360",
      "460",
      "850",
      "850 kombi",
      "C30",
      "C70",
      "C70 Cabrio",
      "C70 Coupé",
      "S40",
      "S60",
      "S70",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "V90",
      "XC60",
      "XC70",
      "XC90"
    ]
  },
  {
    "id": 107,
    "brand": "Fiat",
    "models": [
      "1100",
      "126",
      "500",
      "500L",
      "500X",
      "850",
      "Barchetta",
      "Brava",
      "Cinquecento",
      "Coupé",
      "Croma",
      "Doblo",
      "Doblo Cargo",
      "Doblo Cargo Combi",
      "Ducato",
      "Ducato Van",
      "Ducato Kombi",
      "Ducato Podvozok",
      "Florino",
      "Florino Combi",
      "Freemont",
      "Grande Punto",
      "Idea",
      "Linea",
      "Marea",
      "Marea Weekend",
      "Multipla",
      "Palio Weekend",
      "Panda",
      "Panda Van",
      "Punto",
      "Punto Cabriolet",
      "Punto Evo",
      "Punto Van",
      "Qubo",
      "Scudo",
      "Scudo Van",
      "Scudo Kombi",
      "Sedici",
      "Seicento",
      "Stilo",
      "Stilo Multiwagon",
      "Strada",
      "Talento",
      "Tipo",
      "Ulysse",
      "Uno",
      "X1/9"
    ]
  },
  {
    "id": 109,
    "brand": "Rover",
    "models": ["200", "214", "218", "25", "400", "414", "416", "620", "75"]
  },
  {
    "id": 110,
    "brand": "Smart",
    "models": [
      "Cabrio",
      "City-Coupé",
      "Compact Pulse",
      "Forfour",
      "Fortwo cabrio",
      "Fortwo coupé",
      "Roadster"
    ]
  }
];
